language: php

matrix:
  fast_finish: true
  include:
    - php: '7.1'
    - php: '7.2'
    - php: '7.3'
    - php: '7.4'
    - php: 'nightly'
  allow_failures:
    - php: '7.4'
    - php: 'nightly'

before_install:
 - sudo apt-get -y install flac
 - sudo apt-get -y install atomicparsley

install:
  - composer install --no-interaction

before_script:
 - vendor/bin/phpunit --version

script:
 - vendor/bin/phpunit --bootstrap vendor/autoload.php tests
