language: php

matrix:
  fast_finish: true
  include:
    - php: '5.6'
    - php: '7.0'
    - php: '7.1'
    - php: '7.2'
    - php: '7.3'
    - php: '7.4'
    - php: 'nightly'
  allow_failures:
    - php: '7.4'
    - php: 'nightly'

install:
 - apt-get install flac
 - apt-get install atomicparsley

before_script:
 - vendor/bin/phpunit --version

script:
 - vendor/bin/phpunit --bootstrap vendor/autoload.php tests
