language: php

matrix:
  fast_finish: true
  include:
    - php: '7.1'
    - php: '7.2'
    - php: '7.3'
    - php: '7.4snapshot'
    - php: 'nightly'
      env: IGNORE_PLATFORM_REQS=true
  allow_failures:
    - php: '7.4snapshot'
    - php: 'nightly'

before_install:
 - sudo apt-get -y install flac
 - sudo apt-get -y install atomicparsley

install:
  - if [ "$IGNORE_PLATFORM_REQS" == 'true' ]; then composer install --no-interaction --ignore-platform-reqs;
    else composer install --no-interaction;
    fi

before_script:
 - vendor/bin/phpunit --version

script:
 - vendor/bin/phpunit --bootstrap vendor/autoload.php tests
